// <auto-generated />
using System;
using AccesoDatos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccesoDatos.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20260909222910_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AccesoDatos.Models.Alquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fechadevolucion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fechaentrega")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<int>("Socioid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Socioid");

                    b.ToTable("Alquiler");
                });

            modelBuilder.Entity("AccesoDatos.Models.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AlquilerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlquilerId");

                    b.ToTable("Pelicula");
                });

            modelBuilder.Entity("AccesoDatos.Models.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Dni")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Telefono")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Socio");
                });

            modelBuilder.Entity("AccesoDatos.Models.Alquiler", b =>
                {
                    b.HasOne("AccesoDatos.Models.Socio", "Socio")
                        .WithMany("Alquileres")
                        .HasForeignKey("Socioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("AccesoDatos.Models.Pelicula", b =>
                {
                    b.HasOne("AccesoDatos.Models.Alquiler", null)
                        .WithMany("listapeliculas")
                        .HasForeignKey("AlquilerId");
                });

            modelBuilder.Entity("AccesoDatos.Models.Alquiler", b =>
                {
                    b.Navigation("listapeliculas");
                });

            modelBuilder.Entity("AccesoDatos.Models.Socio", b =>
                {
                    b.Navigation("Alquileres");
                });
#pragma warning restore 612, 618
        }
    }
}
